//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSpace.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KarakterOzellikleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_KarakterOzellikleri()
        {
            this.Tbl_HikayeOzellikleri = new HashSet<Tbl_HikayeOzellikleri>();
        }
    
        public int OzellikID { get; set; }
        public string OzellikAdi { get; set; }
        public string PromptKodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HikayeOzellikleri> Tbl_HikayeOzellikleri { get; set; }
    }
}
