//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.


namespace TimeSpace.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kullanicilar()
        {
            this.Tbl_Hikayeler = new HashSet<Tbl_Hikayeler>();
        }
    
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public string SifreHash { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string Email { get; set; }
        public string KullaniciTipi { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Cinsiyet { get; set; }
        public byte[] ProfilResmi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hikayeler> Tbl_Hikayeler { get; set; }
    }
}
