//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSpace.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HikayeOzellikleri
    {
        public int ID { get; set; }
        public Nullable<int> HikayeID { get; set; }
        public Nullable<int> OzellikID { get; set; }
    
        public virtual Tbl_Hikayeler Tbl_Hikayeler { get; set; }
        public virtual Tbl_KarakterOzellikleri Tbl_KarakterOzellikleri { get; set; }
    }
}
