//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSpace.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Donemler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Donemler()
        {
            this.Tbl_Hikayeler = new HashSet<Tbl_Hikayeler>();
        }
    
        public int DonemID { get; set; }
        public string DonemAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public Nullable<int> BaslangicYili { get; set; }
        public Nullable<int> BitisYili { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hikayeler> Tbl_Hikayeler { get; set; }
    }
}
