//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSpace.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Karakterler
    {
        public int KarakterID { get; set; }
        public string AdSoyad { get; set; }
        public string Aciklama { get; set; }
        public string Gorsel { get; set; }
        public Nullable<int> DonemID { get; set; }
    }
}
